_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.11.8
        t:
            "1":
                - 5
                - 6
                - 53
                - 55
                - 105
            "2":
                - 5
                - 6
                - 53
                - 55
                - 105
            "3":
                - 16
                - 23
                - 31
                - 55
            "4": 3.11.8
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": darwin-arm64
colsample_bytree:
    value: 1
dataset:
    value: XNAS.ITCH
end_date:
    value: "2025-02-28"
eval_metric:
    value: mlogloss
gamma:
    value: 0
learning_rate:
    value: 0.1
len_sequence:
    value: 100
max_depth:
    value: 6
min_child_weight:
    value: 1
n_estimators:
    value: 100
n_samples:
    value: 10000
objective:
    value: multi:softprob
predict_horizon:
    value: 10
random_state:
    value: 42
start_date:
    value: "2018-05-01"
subsample:
    value: 1
symbol:
    value: AAPL
tree_method:
    value: auto
